// src/typography/TypographyData.js

export const TYPOGRAPHY_STYLES = [
  {
    name: "Display Large",
    fontSize: 48,
    letterSpacing: 0,
    lineHeight: 1.1,
    italic: false,
    fontWeight: 700,
    color: "#222222",
    fontFamily: "Primary Family",
    example: "Welcome to Your App!",
  },
  {
    name: "Display Medium",
    fontSize: 36,
    letterSpacing: 0,
    lineHeight: 1.15,
    italic: false,
    fontWeight: 700,
    color: "#222222",
    fontFamily: "Primary Family",
    example: "Design for everyone.",
  },
  {
    name: "Display Small",
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 1.15,
    italic: false,
    fontWeight: 600,
    color: "#222222",
    fontFamily: "Primary Family",
    example: "New features!",
  },
  {
    name: "Headline Large",
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 1.2,
    italic: false,
    fontWeight: 700,
    color: "#222222",
    fontFamily: "Primary Family",
    example: "Card Headline",
  },
  {
    name: "Headline Medium",
    fontSize: 20,
    letterSpacing: 0,
    lineHeight: 1.2,
    italic: false,
    fontWeight: 600,
    color: "#222222",
    fontFamily: "Primary Family",
    example: "Subsection Title",
  },
  {
    name: "Headline Small",
    fontSize: 18,
    letterSpacing: 0,
    lineHeight: 1.2,
    italic: false,
    fontWeight: 600,
    color: "#222222",
    fontFamily: "Primary Family",
    example: "Widget Title",
  },
  {
    name: "Title Large",
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 1.25,
    italic: false,
    fontWeight: 500,
    color: "#222222",
    fontFamily: "Primary Family",
    example: "Card Title",
  },
  {
    name: "Title Medium",
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 1.25,
    italic: false,
    fontWeight: 500,
    color: "#222222",
    fontFamily: "Secondary Family",
    example: "Get Started",
  },
  {
    name: "Title Small",
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 1.25,
    italic: false,
    fontWeight: 500,
    color: "#222222",
    fontFamily: "Secondary Family",
    example: "Learn More",
  },
  {
    name: "Label Large",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 1.25,
    italic: false,
    fontWeight: 400,
    color: "#222222",
    fontFamily: "Secondary Family",
    example: "Action",
  },
  {
    name: "Label Medium",
    fontSize: 12,
    letterSpacing: 0.1,
    lineHeight: 1.25,
    italic: false,
    fontWeight: 400,
    color: "#222222",
    fontFamily: "Secondary Family",
    example: "Status",
  },
  {
    name: "Label Small",
    fontSize: 11,
    letterSpacing: 0.1,
    lineHeight: 1.2,
    italic: false,
    fontWeight: 300,
    color: "#222222",
    fontFamily: "Secondary Family",
    example: "Optional",
  },
  {
    name: "Body Large",
    fontSize: 16,
    letterSpacing: 0,
    lineHeight: 1.5,
    italic: false,
    fontWeight: 400,
    color: "#222222",
    fontFamily: "Secondary Family",
    example: "This is a demo landing page using your design system.",
  },
  {
    name: "Body Medium",
    fontSize: 14,
    letterSpacing: 0,
    lineHeight: 1.5,
    italic: false,
    fontWeight: 400,
    color: "#222222",
    fontFamily: "Secondary Family",
    example: "This card demonstrates secondary backgrounds and brand color for the border.",
  },
  {
    name: "Body Small",
    fontSize: 12,
    letterSpacing: 0,
    lineHeight: 1.4,
    italic: false,
    fontWeight: 300,
    color: "#222222",
    fontFamily: "Secondary Family",
    example: "© 2025 Your Company Name · All rights reserved.",
  },
];

export const TYPOGRAPHY_USE_CASES = {
  "Display Large": "Landing page headline. Example: Welcome to Your App!",
  "Display Medium": "Section hero titles. Example: Design for everyone.",
  "Display Small": "Banner headings. Example: New features!",
  "Headline Large": "Page or card headers. Example: Card Headline",
  "Headline Medium": "Subsection headings. Example: Subsection Title",
  "Headline Small": "Widget titles. Example: Widget Title",
  "Title Large": "Card titles. Example: Card Title",
  "Title Medium": "Button text, input labels. Example: Get Started",
  "Title Small": "Footer text, micro-labels. Example: Learn More",
  "Label Large": "Large chips, navigation tabs. Example: Action",
  "Label Medium": "Medium-sized labels, chip text. Example: Status",
  "Label Small": "Table headers, filter pills. Example: Optional",
  "Body Large": "Main body copy. Example: This is a demo landing page using your design system.",
  "Body Medium": "Paragraph text, modal content. Example: This card demonstrates secondary backgrounds and brand color for the border.",
  "Body Small": "Captions, footnotes, form help text. Example: © 2025 Your Company Name · All rights reserved.",
};