// Example: Map color/typography role to location(s) in your app UI
export const COLOR_LOCATIONS = {
    "brand - primary": "Landing Page, Card UI",
    "brand - secondary": "Card UI",
    "brand - tertiary": "Landing Page",
    "brand - alternate": "Landing Page",
    "utility - primary text": "Landing Page, Card UI, Alerts & Status",
    "utility - secondary text": "Landing Page, Card UI",
    "utility - primary bg": "Landing Page, Alerts & Status",
    "utility - secondary bg": "Card UI",
    "accent - accent 1": "Landing Page",
    "accent - accent 2": "Card UI",
    "accent - accent 3": "Card UI",
    "accent - accent 4": "Landing Page",
    "semantic - success": "Alerts & Status",
    "semantic - error": "Alerts & Status",
    "semantic - warning": "Alerts & Status",
    "semantic - info": "Alerts & Status",
  };
  
  export const TYPOGRAPHY_LOCATIONS = {
    "Display Large":      { location: "Landing page headline",        example: "Welcome to Your App!" },
    "Display Medium":     { location: "Section hero titles",          example: "Design for everyone." },
    "Display Small":      { location: "Banner headings",              example: "New features!" },
    "Headline Large":     { location: "Page or card headers",         example: "Card Headline" },
    "Headline Medium":    { location: "Subsection headings",          example: "Subsection Title" },
    "Headline Small":     { location: "Widget titles",                example: "Widget Title" },
    "Title Large":        { location: "Card titles",                  example: "Card Title" },
    "Title Medium":       { location: "Button text, input labels",    example: "Get Started" },
    "Title Small":        { location: "Footer text, micro-labels",    example: "Learn More" },
    "Label Large":        { location: "Large chips, navigation tabs", example: "Action" },
    "Label Medium":       { location: "Medium-sized labels, chip text", example: "Status" },
    "Label Small":        { location: "Table headers, filter pills",  example: "Optional" },
    "Body Large":         { location: "Main body copy",               example: "This is a demo landing page using your design system." },
    "Body Medium":        { location: "Paragraph text, modal content", example: "This card demonstrates secondary backgrounds and brand color for the border." },
    "Body Small":         { location: "Captions, footnotes, form help text", example: "© 2025 Your Company Name · All rights reserved." },
  };