export const FONT_FAMILIES = [
    { label: "Primary Family", value: "Poppins"},
    { label: "Secondary Family", value: "Inter"},
];

export const FONT_WEIGHTS = [
    { label: "Thin", value: 100 },
    { label: "Extra Light", value: 200 },
    { label: "Light", value: 300 },
    { label: "Normal", value: 400 },
    { label: "Medium", value: 500 },
    { label: "Semi Bold", value: 600 },
    { label: "Bold", value: 700 },
    { label: "Extra Bold", value: 800 },
    { label: "Black", value: 900 },
];

export const TEXT_COLORS = [
    { label: "Primary Text", value: "#0f1420" },
    { label: "Secondary Text", value: "#757b7c" },
    { label: "Accent 1", value: "#5c5cbe" },
];

export const ALIGNMENTS =[
    { label: "Left", value: "left" },
    { label: "Center", value: "center" },
    { label: "Right", value: "right"},
];

// Each style type with default config
export const TYPOGRAPHY_STYLES = [

    {
        name: "Display Large",
        alignment: "center",
        fontSize: 48,
        fontWeight: 700,
        color: "#0f1420",
        fontFamily: "Primary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Display Medium",
        alignment: "center",
        fontSize: 36,
        fontWeight: 700,
        color: "#0f1420",
        fontFamily: "Primary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Display Small",
        alignment: "center",
        fontSize: 28,
        fontWeight: 600,
        color: "#0f1420",
        fontFamily: "Primary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },

    {
        name: "Headline Large",
        alignment: "center",
        fontSize: 24,
        fontWeight: 700,
        color: "#0f1420",
        fontFamily: "Primary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Headline Medium",
        alignment: "center",
        fontSize: 20,
        fontWeight: 600,
        color: "#0f1420",
        fontFamily: "Primary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Headline Small",
        alignment: "center",
        fontSize: 18,
        fontWeight: 600,
        color: "#0f1420",
        fontFamily: "Primary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },

    {
        name: "Title Large",
        alignment: "center",
        fontSize: 16,
        fontWeight: 500,
        color: "#0f1420",
        fontFamily: "Primary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Title Medium",
        alignment: "center",
        fontSize: 16,
        fontWeight: 500,
        color: "#0f1420",
        fontFamily: "Secondary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Title Small",
        alignment: "center",
        fontSize: 14,
        fontWeight: 500,
        color: "#0f1420",
        fontFamily: "Secondary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },

    {
        name: "Label Large",
        alignment: "center",
        fontSize: 14,
        fontWeight: 400,
        color: "#0f1420",
        fontFamily: "Secondary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Label Medium",
        alignment: "center",
        fontSize: 12,
        fontWeight: 400,
        color: "#0f1420",
        fontFamily: "Secondary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Label Small",
        alignment: "center",
        fontSize: 11,
        fontWeight: 300,
        color: "#0f1420",
        fontFamily: "Secondary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },

    {
        name: "Body Large",
        alignment: "center",
        fontSize: 16,
        fontWeight: 400,
        color: "#0f1420",
        fontFamily: "Secondary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Body Medium",
        alignment: "center",
        fontSize: 14,
        fontWeight: 400,
        color: "#0f1420",
        fontFamily: "Secondary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },
    {
        name: "Body Small",
        alignment: "center",
        fontSize: 12,
        fontWeight: 300,
        color: "#0f1420",
        fontFamily: "Secondary Family",
        letterSpacing: 0,
        italic: false,
        lineHeight: 1.2,
    },

]